project_name: axiom-cloudwatch-lambda

builds:
  - id: axiom-cloudwatch-lambda
    goos:
      - linux
    goarch:
      - amd64
    binary: axiom-cloudwatch-lambda
    main: ./cmd/axiom-cloudwatch-lambda
    env:
      - CGO_ENABLED=0
    flags:
      - -buildmode=pie
      - -installsuffix=cgo
      - -trimpath
      - -tags="osusergo netgo static_build"
    ldflags:
      - -s -w -extldflags "-fno-PIC -static -Wl -z now -z relro"
      - -X github.com/axiomhq/pkg/version.release={{ .Version }}
      - -X github.com/axiomhq/pkg/version.revision={{ .ShortCommit }}
      - -X github.com/axiomhq/pkg/version.buildDate={{ .CommitDate }}
      - -X github.com/axiomhq/pkg/version.buildUser=goreleaser
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: axiom-cloudwatch-lambda
    builds:
      - axiom-cloudwatch-lambda
    name_template: "{{ .ProjectName }}_{{ .Version }}"
    wrap_in_directory: true
    format: tar.gz
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

milestones:
  - repo:
      owner: axiomhq
      name: axiom-cloudwatch-lambda
    close: true
    fail_on_error: false

release:
  github:
    owner: axiomhq
    name: axiom-cloudwatch-lambda
  prerelease: auto
  name_template: "Axiom Cloudwatch Lambda v{{ .Version }}"
