Parameters:
  AxiomToken:
    Description: The Token of User in Axiom. Must start with xaat- or xait-.
    Type: String
    NoEcho: true
    AllowedPattern: "^(xaat-|xait-).*"
  AxiomURL:
    Type: String
    Default: "https://cloud.axiom.co"
    AllowedPattern: ".+" # required
    Description: The URL of Axiom endpoint (without trailing /). Defaults to "https://cloud.axiom.co".
  AxiomDataset:
    Type: String
    Description: The Name of the Dataset in Axiom to push events to.
    AllowedPattern: ".+" # required
  CloudWatchLogGroupName:
    Type: String
    Description: The name of the AWS Cloudwatch Log Group to subscribe to.
    AllowedPattern: ".+" # required
  DisableJSON:
    Type: String
    AllowedValues:
      - true
      - false
    Default: false
    Description: Whether or not disable json logs. defaults to false.
Resources:
  LogGroupSubscriptionFilter:
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      DestinationArn: !GetAtt
        - LogsLambda
        - Arn
      FilterPattern: ""
      LogGroupName: !Ref 'CloudWatchLogGroupName'
  LogsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
  LogsLambda:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.9
      FunctionName: axiom-cloudwatch-lambda
      Handler: index.lambda_handler
      Code:
        ZipFile: |
          # DO NOT EDIT
          # CI will replace these comments with the code from ./handler.py
      Role: !GetAtt
        - LogsRole
        - Arn
      Environment:
        Variables:
          AXIOM_TOKEN: !Ref 'AxiomToken'
          AXIOM_DATASET: !Ref 'AxiomDataset'
          AXIOM_URL: !Ref 'AxiomURL'
          DISABLE_JSON: !Ref DisableJSON
  LogsLambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - LogsLambda
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref 'LogsLambda'
      Principal: !Sub
        - 'logs.${Region}.amazonaws.com'
        - Region: !Ref 'AWS::Region'
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: !Sub
        - 'arn:aws:logs:${Region}:${AccountID}:log-group:${LogGroupName}:*'
        - AccountID: !Ref 'AWS::AccountId'
          Region: !Ref 'AWS::Region'
          LogGroupName: !Ref 'CloudWatchLogGroupName'
