Parameters:
  LambdaFunctionName:
    Type: String
    Description: Name of the AWS Lambda Function.
    Default: cloudwatch-backfiller-axiom
    AllowedPattern: ".+" # required
  AxiomCloudWatchLambdaIngesterARN:
    Type: String
    Description: The ARN of the AWS Lambda Function that is used to ingest data to axiom.
    AllowedPattern: ".+" # required
  CloudWatchLogGroupsPrefix:
    Type: String
    Description: The Prefix of cloudwatch log groups to subscribe to the AWS Lambda ingester.
    Default: "" # all
Resources:
  BackfillerPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:DeleteSubscriptionFilter
              - logs:PutSubscriptionFilter
              - logs:DescribeLogGroups
              - lambda:AddPermission
              - lambda:RemovePermission
            Effect: Allow
            Resource: '*'
      PolicyName: axiom-cloudwatch-backfiller-lambda-policy
      Roles:
        - !Ref 'BackfillerRole'
  BackfillerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
  BackfillerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Runtime: python3.9
      Handler: index.lambda_handler
      Timeout: 300
      Code:
        ZipFile: |
          # DO NOT EDIT
          # CI will replace these comments with the code from ./backfill.py
      Role: !GetAtt
        - BackfillerRole
        - Arn
      Environment:
        Variables:
          AXIOM_CLOUDWATCH_LAMBDA_INGESTER_ARN: !Ref 'AxiomCloudWatchLambdaIngesterARN'
          LOG_GROUP_PREFIX: !Ref 'CloudWatchLogGroupsPrefix'
  BackfillerInvoker:
    Type: AWS::CloudFormation::CustomResource
    DependsOn: BackfillerLambda
    Version: "1.0"
    Properties:
      ServiceToken: !GetAtt BackfillerLambda.Arn
      StackName: !Ref AWS::StackName
