Description: Axiom CloudWatch Forwarder Lambda
AWSTemplateFormatVersion: 2010-09-09
Transform: "AWS::LanguageExtensions"
Parameters:
  AxiomToken:
    Description: The API token with ingest permission to dataset. Must start with xaat- or xait-.
    Type: String
    NoEcho: true
    AllowedPattern: "^(xaat-|xait-).*"
  AxiomURL:
    Type: String
    Default: "https://api.axiom.co"
    AllowedPattern: ".+" # required
    Description: The URL of Axiom endpoint (without trailing /). Defaults to "https://api.axiom.co".
  AxiomDataset:
    Type: String
    Description: The Name of the dataset in Axiom to push events to.
    AllowedPattern: ".+" # required
  LambdaFunctionName:
    Type: String
    Description: Name of the AWS Lambda function.
    Default: axiom-cloudwatch-forwarder
    AllowedPattern: ".+" # required
  DataTags:
    Type: String
    Description: Tags to be included with the data ingested into axiom. e.g. <key1>=<value1>,<key2>=<value2>.
Resources:
  AxiomCloudWatchForwarderRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - "sts:AssumeRole"
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
  AxiomCloudWatchForwarder:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Runtime: python3.9
      Handler: index.lambda_handler
      Code:
        ZipFile: |
          # DO NOT EDIT
          # CI will replace these comments with the code from ./handler.py
      Role: !GetAtt
        - AxiomCloudWatchForwarderRole
        - Arn
      Environment:
        Variables:
          AXIOM_TOKEN: !Ref "AxiomToken"
          AXIOM_DATASET: !Ref "AxiomDataset"
          AXIOM_URL: !Ref "AxiomURL"
          DISABLE_JSON: !Ref DisableJSON
          DATA_TAGS: !Ref DataTags
Outputs:
  AxiomCloudWatchForwarderARN:
    Description: The ARN of the created Forwarder Lambda
    Value: !GetAtt AxiomCloudWatchForwarder.Arn
