Description: A Lambda function to auto subscribe Axiom CloudWatch Forwarder to new log groups.
Parameters:
  AxiomCloudWatchForwarderLambdaARN:
    Type: String
    Description: The ARN of the AWS Lambda function that is used to forward logs to Axiom.
    AllowedPattern: ".+" # required
  CloudWatchLogGroupsPrefix:
    Type: String
    Description: The prefix of the CloudWatch log groups that will trigger the Axiom CloudWatch Forwarder Lambda.
    Default: "" # all
  AxiomLambdaLogRetention:
    Type: "Number"
    Description: "The number of days to retain CloudWatch logs for the created Lambda functions."
    Default: 1
  EnableCloudTrail:
    Description: "Enable Cloudtrail for CloudWatch CreateLogGroup event notification? If already enabled, choose 'false'"
    Default: true
    Type: String
    AllowedValues: [true, false]
Conditions:
  ShouldEnableCloudTrail: !Equals [true, !Ref EnableCloudTrail]
Resources:
  ListenerS3Bucket:
    Condition: ShouldEnableCloudTrail
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: BucketOwnerFullControl
      BucketName: !Join ["-", [!Ref AWS::StackName, "cloudtrail"]]
  ListenerS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: ShouldEnableCloudTrail
    DependsOn: ListenerS3Bucket
    Properties:
      Bucket: !Ref ListenerS3Bucket
      PolicyDocument:
        {
          "Version": "2012-10-17",
          "Statement":
            [
              {
                "Sid": "AWSCloudTrailAclCheck20150319",
                "Effect": "Allow",
                "Principal": { "Service": "cloudtrail.amazonaws.com" },
                "Action": "s3:GetBucketAcl",
                "Resource": !GetAtt ["ListenerS3Bucket", "Arn"],
              },
              {
                "Sid": "AWSCloudTrailWrite20150319",
                "Effect": "Allow",
                "Principal": { "Service": "cloudtrail.amazonaws.com" },
                "Action": "s3:PutObject",
                "Resource":
                  !Join [
                    "",
                    [
                      !GetAtt ["ListenerS3Bucket", "Arn"],
                      "/AWSLogs/",
                      { "Ref": "AWS::AccountId" },
                      "/*",
                    ],
                  ],
                "Condition":
                  {
                    "StringEquals":
                      { "s3:x-amz-acl": "bucket-owner-full-control" },
                  },
              },
            ],
        }
  ListenerCloudTrail:
    Type: AWS::CloudTrail::Trail
    Condition: ShouldEnableCloudTrail
    DependsOn: ListenerS3BucketPolicy
    Properties:
      EnableLogFileValidation: false
      IsLogging: true
      S3BucketName: !Ref ListenerS3Bucket
      TrailName: !Join ["-", [!Ref AWS::StackName, { "Ref": "AWS::AccountId" }]]
  ListenerEventRule:
    DependsOn: ListenerLambda
    Type: AWS::Events::Rule
    Properties:
      Description: Axiom log group auto subscription event rule.
      EventPattern:
        source: ["aws.logs"]
        detail-type: ["AWS API Call via CloudTrail"]
        detail:
          eventSource: ["logs.amazonaws.com"]
          eventName: ["CreateLogGroup"]
      Name:
        "Fn::Join":
          ["-", [{ "Ref": "AWS::StackName" }, "auto-subscription-rule"]]
      Targets:
        - Id: !Join ["-", [!Ref "AWS::StackName", "auto-subscription-rule"]]
          Arn: !GetAtt ["ListenerLambda", "Arn"]
  ListenerPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:DeleteSubscriptionFilter
              - logs:PutSubscriptionFilter
              - logs:DescribeLogGroups
              - lambda:AddPermission
              - lambda:RemovePermission
              - lambda:InvokeFunction
              - lambda:GetFunction
              - logs:DescribeLogStreams
              - logs:DescribeSubscriptionFilters
              - logs:FilterLogEvents
              - logs:GetLogEvents
            Effect: Allow
            Resource: "*"
      PolicyName: axiom-cloudwatch-listener-policy
      Roles:
        - !Ref "ListenerLambda"
  ListenerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - "sts:AssumeRole"
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - logs.amazonaws.com
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
  ListenerLambda:
    Type: AWS::Lambda::Function
    DependsOn:
      - ListenerRole
    Properties:
      FunctionName: !Sub "${AWS::StackName}"
      Runtime: python3.9
      Handler: index.lambda_handler
      Code:
        ZipFile: |
          # DO NOT EDIT
          # CI will replace these comments with the code from ./logs_subscriber.py
      Role: !GetAtt
        - ListenerRole
        - Arn
      Description: Axiom CloudWatch Automatic log groups listener lambda
      Environment:
        Variables:
          AXIOM_CLOUDWATCH_FORWARDER_LAMBDA_ARN: !Ref "AxiomCloudWatchForwarderLambdaARN"
          LOG_GROUP_PREFIX: !Ref "CloudWatchLogGroupsPrefix"
  ListenerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: { "Fn::GetAtt": ["ListenerLambda", "Arn"] }
      Principal: "events.amazonaws.com"
      SourceAccount:
        Ref: AWS::AccountId
      SourceArn: !GetAtt ["ListenerEventRule", "Arn"]
  ListenerLogGroup:
    DependsOn: ["ListenerRole"]
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    Properties:
      LogGroupName: !Sub "/aws/axiom/${AWS::StackName}"
      RetentionInDays:
        Ref: "AxiomLambdaLogRetention"
