Description: A lambda that removes subscription filters for provided log groups
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Unsubscriber lambda"
        Parameters:
          - LambdaFunctionName
      - Label:
          default: "Forwarder lambda"
        Parameters:
          - AxiomCloudWatchForwarderLambdaARN
      - Label: 
          default: "Log groups to unsubscribe from"
        Parameters:
          - CloudWatchLogGroupsNames
          - CloudWatchLogGroupsPrefix
          - CloudWatchLogGroupsPattern

Parameters:
  LambdaFunctionName:
    Type: String
    Description: Name of the AWS Lambda function.
    Default: axiom-cloudwatch-unsubscriber
    AllowedPattern: ".+" # required
  AxiomCloudWatchForwarderLambdaARN:
    Type: String
    Description: The ARN of the Axiom CloudWatch Forwarder Lambda function used to ship logs to Axiom.
    AllowedPattern: ".+" # required
  CloudWatchLogGroupsNames:
    Type: String
    Description: A comma separated list of CloudWatch log groups to unsubscribe from.
    Default: "" # all
  CloudWatchLogGroupsPrefix:
    Type: String
    Description: The Prefix of CloudWatch log groups to unsubscribe from.
    Default: "" # all
  CloudWatchLogGroupsPattern:
    Type: String
    Description: A regular expression pattern of CloudWatch log groups to unsubscribe from.
    Default: "" # all
Resources:
  UnsubscriberPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:DeleteSubscriptionFilter
              - logs:PutSubscriptionFilter
              - logs:DescribeLogGroups
              - lambda:AddPermission
              - lambda:RemovePermission
            Effect: Allow
            Resource: '*'
      PolicyName: axiom-cloudwatch-unsubscriber-lambda-policy
      Roles:
        - !Ref 'UnsubscriberRole'
  UnsubscriberRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
  SubscriberLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Runtime: python3.9
      Handler: index.lambda_handler
      Timeout: 300
      Code:
        ZipFile: |
          # DO NOT EDIT
          # CI will replace these comments with the code from ./unsubscriber.py
      Role: !GetAtt
        - UnsubscriberRole
        - Arn
      Environment:
        Variables:
          AXIOM_CLOUDWATCH_FORWARDER_LAMBDA_ARN: !Ref 'AxiomCloudWatchForwarderLambdaARN'
          LOG_GROUP_NAMES: !Ref 'CloudWatchLogGroupsNames'
          LOG_GROUP_PREFIX: !Ref 'CloudWatchLogGroupsPrefix'
          LOG_GROUP_PATTERN: !Ref 'CloudWatchLogGroupsPattern'
  SubscriberInvoker:
    Type: AWS::CloudFormation::CustomResource
    DependsOn: SubscriberLambda
    Version: "1.0"
    Properties:
      ServiceToken: !GetAtt UnsubscriberLambda.Arn
      StackName: !Ref AWS::StackName
